version: '2.3'
services:
  rest-api:
    build: .
    image: moono/gm-rest-api-server:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    pid: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/proc:/host_proc:ro"
    ports:
      - "3032:3032"
    command: ["python", "simple_rest_api.py"]