version: '2.3'
services:
  rest-api:
    build: .
    image: moono/gm-rest-api-server:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - FLASK_APP=simple_rest_api.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    pid: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/proc:/host_proc:ro"
    ports:
      - "3032:3032"